display_errors = 0
short_open_tag = On
variables_order = "GPCS"
request_order = "GP"

memory_limit = 512M
max_execution_time = 600
max_input_time = 300
post_max_size = 50M
upload_max_filesize = 50M
max_input_vars = 5000
expose_php = Off

date.timezone = Asia/Tehran
extension = timezonedb

opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 2
