[Definition]
failregex = ^(.*)postfix/(submission|smtps)/smtpd(.*): warning:.*\[<HOST>\]: SASL (LOGIN|PLAIN) authentication failed.*$
            ^(.*)postfix/(submission|smtps)/smtpd(.*): warning: .*\[<HOST>\]: SASL .* authentication failed.*$
ignoreregex =
